name: Test

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and its submodules
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install the Foundry toolchain
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Cache Forge dependencies (if applicable)
      - name: Cache Forge Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      # Run Forge Build to compile the project and check for sizes
      - name: Run Forge Build
        run: |
          forge --version
          forge build --sizes
        id: build

      # Run Forge tests and output detailed logs for troubleshooting
      - name: Run Forge Tests
        run: |
          forge test -vvv
        id: test
        continue-on-error: false  # Ensure that failing tests stop the pipeline
